baseURL = "https://dan.krizanek.com"
languageCode = "en-us"
title = "Dan Krizanek"
theme = "hugo-resume"

[params]
    firstName = "Dan"
    lastName = "Krizanek"
    address = "Detroit, MI"
    contactNote = "Infrastructure/Cloud/Automation Engineer"
    profileImage = "img/TechChat.png"
    email = "Dan@Krizanek.com"
    description = "An innovative and hardworking technology professional with years of experience in infrastructure and cloud technologies in the enterprise space"
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true

    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/dankrizanek/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/dkrizanek"

[params.google.analytics]
    trackerID = "XX-123446-01"
