baseURL = "https://dan.krizanek.com"
languageCode = "en-us"
title = "Dan Krizanek"
theme = "hugo-resume"

[params]
    firstName = "Dan"
    lastName = "Krizanek"
    address = "Detroit, MI"
    contactNote = "Infrastructure/Cloud/Automation Engineer"
    profileImage = "img/TechChat.png"
    email = "email@domain.com"
    description = "Software Platform Engineer with experience leveraging agile, DevOps, and CI/CD to manage large scale distributed platforms both on prem and in public cloud."
    favicon = "images/favicon.ico"
    # what sections
    showSkills = true
    showProjects = false
    showOpenSource = false
    showPublications = false
    showExperience = true
    showEducation = true

    showQr = true

[[params.handles]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/edwardwebb/"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/eddiewebb/"

[params.google.analytics]
    trackerID = "XX-123446-01"
